### ISSUE TITLE
System.NullReferenceException when connecting to CRM Online

### ISSUE THREAD

**Issue by TNSilverbear** [kenakamu/CRMLinqPadDriverWebAPI#4] opened 2016-09-09 07:59 UTC
When creating a connection to as CRM Online instance I am receiving a System.NullReferenceException error thrown by Linqpad. This occurs during or potentially just after the dialog is showing the registering application message.

Any idea what may be causing this or where I could find more information to diagnose the issue?

**Comment by kenakamu** [comment] 2016-09-09 08:53
Thanks for report.  Dis you try the latest version?

**Comment by kenakamu** [comment] 2016-09-09 08:54
Tapped wrong button and closed this accidentally. Reopened

**Comment by TNSilverbear** [comment] 2016-09-09 09:10
I've just re-downloaded the latest version an updated and still get the same issue I'm afraid.

**Comment by kenakamu** [comment] 2016-09-09 13:14
Okay. Please let me know now detail repro steps and your environment detail so that I can think about the root cause.

**Comment by rajyraman** [comment] 2016-10-26 11:17
I am having the exact same issue. It was working before in Windows 8 couple of months back. I have tried in both LinqPad 4/5. I was initially getting NullReference and now, no organisation is being added after "Registering Application" dialog.

**Comment by kenakamu** [comment] 2016-11-14 09:57
please try the latest version (1.3) and let me know if it works

**Comment by TNSilverbear** [comment] 2016-11-14 10:23
That appears to have resolved this issue, thank you. I am now receiving a different error message which I will raise as a separate issue.

**Comment by kenakamu** [comment] 2016-11-14 14:46
Let me close it then.

**Closed as completed by kenakamu** 2016-11-14 14:46 UTC
